"""
Configuration and parameter definitions for CivMini game.

Defines the parameter space θ that can be optimized for game balance.
"""

from dataclasses import dataclass, field
from typing import Dict, Any, Tuple, List


@dataclass
class GameConfig:
    """Configuration for CivMini game parameters."""
    
    # Game settings
    map_size: int = 7
    max_turns: int = 20
    
    # Model settings
    model_name: str = "OpenGVLab/InternVL2-1B"  # Can use InternVL-Chat-0.5B or similar
    max_new_tokens: int = 256
    temperature: float = 0.7
    device: str = "cuda"
    
    # RAG settings
    rag_top_k: int = 3
    
    # Optimization settings
    n_optimization_iterations: int = 20
    n_games_per_eval: int = 5
    
    # LLM settings
    use_llm_checker: bool = True  # Enable checker by default
    max_action_retries: int = 2   # Max retries when checker finds invalid actions


def get_default_theta() -> Dict[str, float]:
    """
    Get default game balance parameters θ.
    
    These parameters control game balance and can be optimized.
    
    New rules:
    - Both sides start with 1 city (cannot build new cities)
    - Cities are immobile units with HP, can be attacked
    - Empire: Farmers (gather only) + Soldiers (combat only)
    - Nomads: Cavalry (combat only, gains resources by killing)
    - Win by destroying enemy city or highest score at max turns
    
    Returns:
        Dictionary of parameter names to values
    """
    return {
        # Resource gathering rates
        "empire_farmer_gather_amount": 2,  # Empire farmer gather rate
        
        # Nomad combat economy (NEW MECHANIC)
        "nomads_kill_resource_gain": 3,  # Resources gained when Nomads kill enemy
        
        # Combat parameters (unified battle bonus for simplicity)
        "empire_battle_base_damage": 1,  # Empire soldier/city base damage
        "nomads_battle_base_damage": 2,  # Nomads cavalry/city base damage
        "battle_bonus": 1,  # Unified battle bonus multiplier
        
        # Unit health points
        "empire_soldier_hp": 8,  # Soldier and city HP
        "nomads_cavalry_hp": 6,   # Cavalry and city HP
        
        # Movement parameters
        "empire_unit_move_points": 1,     # All Empire units move the same
        "nomads_cavalry_move_points": 2,  # Cavalry movement (more mobile)
        
        # Unit production costs (per civilization)
        "empire_unit_production_cost": 4,  # Cost to produce Empire units (farmer/soldier)
        "nomads_unit_production_cost": 4,  # Cost to produce Nomads cavalry
        
        # City production parameters (per civilization)
        "empire_city_resource_production": 3,  # Resources generated by Empire city
        "nomads_city_resource_production": 3,  # Resources generated by Nomads city
        
        # Scoring parameters
        "score_per_resource": 0.1,
        "score_per_battle_won": 1,
        "score_per_surviving_unit": 1,
        
        # Game length (now optimizable!)
        # "max_turns": 20,  # Maximum turns before game ends
        
        # Initial setup
        "initial_resources": 5,  # Starting resources for both sides
        "empire_initial_farmers": 1,   # Empire starts with 1 farmer (fixed)
        "empire_initial_soldiers": 1,  # Empire starts with 1 soldier (fixed)
        "nomads_initial_cavalry": 2,   # Nomads starts with 2 cavalry (fixed)
    }


def get_theta_bounds() -> Dict[str, Tuple[float, float]]:
    """
    Get search bounds for each parameter in θ.
    
    Returns:
        Dictionary mapping parameter names to (min, max) tuples
    """
    return {
        # Economy
        "empire_farmer_gather_amount": (1, 5),
        "nomads_kill_resource_gain": (1, 10),  # NEW
        
        # Combat parameters
        "empire_battle_base_damage": (1, 5),
        "nomads_battle_base_damage": (1, 5),
        # "battle_bonus": (0.5, 2.0),
        
        # Unit HP
        "empire_soldier_hp": (4, 16),
        "nomads_cavalry_hp": (4, 16),
        
        # # Movement
        # "empire_unit_move_points": (1.0, 3.0),
        # "nomads_cavalry_move_points": (1.0, 4.0),
        
        # Unit costs (per civilization)
        "empire_unit_production_cost": (2, 10),
        "nomads_unit_production_cost": (2, 10),
        
        # # City production (per civilization)
        # "empire_city_resource_production": (0.5, 3.0),
        # "nomads_city_resource_production": (0.5, 3.0),
        
        # Scoring
        "score_per_resource": (0.1, 0.5),
        "score_per_battle_won": (1, 5),
        "score_per_surviving_unit": (1, 5),
        
        # Game length (optimizable)
        # "max_turns": (10.0, 50.0),
        
        # # Initial setup
        "initial_resources": (2, 10),
        # "empire_initial_farmers": (0.0, 3.0),
        # "empire_initial_soldiers": (0.0, 3.0),
        # "nomads_initial_cavalry": (1.0, 4.0),
    }

def theta_to_array(theta: Dict[str, float]) -> list:
    """Convert theta dict to ordered array for optimization."""
    keys = sorted(theta.keys())
    return [theta[k] for k in keys]


def array_to_theta(arr: list) -> Dict[str, float]:
    """Convert ordered array back to theta dict."""
    default_theta = get_default_theta()
    keys = sorted(default_theta.keys())
    return {k: float(v) for k, v in zip(keys, arr)}


def get_optimizable_params() -> List[str]:
    """
    Get list of parameters that should be optimized.
    
    Parameters NOT in this list will be kept at their default values during optimization.
    
    Returns:
        List of parameter names to optimize
    """
    return [
        # Economy (gathering vs killing)
        "empire_farmer_gather_amount",
        "nomads_kill_resource_gain",
        
        # Combat parameters (optimize combat balance)
        "empire_battle_base_damage",
        "nomads_battle_base_damage",
        # "battle_bonus",
        
        # Unit HP (optimize unit durability)
        "empire_soldier_hp",
        "nomads_cavalry_hp",
        
        # Unit costs (per civilization for independent optimization)
        "empire_unit_production_cost",
        "nomads_unit_production_cost",
        
        # # City production (per civilization)
        # "empire_city_resource_production",
        # "nomads_city_resource_production",
        
        # Scoring parameters (optimize victory conditions balance)
        "score_per_resource",
        "score_per_battle_won",
        "score_per_surviving_unit",
        
        # Initial conditions (optimize starting balance)
        "initial_resources",
        # "empire_initial_farmers",
        # "empire_initial_soldiers",
        # "nomads_initial_cavalry",
        
        # Movement parameters - 暂时不优化，保持固定值
        # "empire_unit_move_points",
        # "nomads_cavalry_move_points",
    ]


def get_fixed_params() -> Dict[str, float]:
    """
    Get parameters that should NOT be optimized (kept at default values).
    
    Returns:
        Dictionary of fixed parameter names to their values
    """
    default_theta = get_default_theta()
    optimizable = set(get_optimizable_params())
    
    return {
        k: v for k, v in default_theta.items()
        if k not in optimizable
    }


def get_param_precision(param_name: str) -> float:
    """
    Get the discretization precision for a parameter.
    
    Rules:
    - If default value is integer (1, 2, 3) -> precision = 1.0
    - If default value has 1 decimal (1.2, 2.5) -> precision = 0.1
    - If default value has 2 decimals (0.15, 1.25) -> precision = 0.01
    
    Args:
        param_name: Parameter name
        
    Returns:
        Precision value (1.0, 0.1, or 0.01)
    """
    default_theta = get_default_theta()
    if param_name not in default_theta:
        return 1.0
    
    value = default_theta[param_name]
    
    # Check if value is effectively an integer
    if abs(value - round(value)) < 1e-9:
        return 1.0
    
    # Check decimal places
    value_str = f"{value:.10f}".rstrip('0').rstrip('.')
    if '.' in value_str:
        decimal_places = len(value_str.split('.')[1])
        if decimal_places <= 1:
            return 0.1
        else:
            return 0.01
    
    return 1.0


def discretize_theta(theta: Dict[str, float]) -> Dict[str, float]:
    """
    Discretize theta values according to their precision.
    
    Args:
        theta: Continuous parameter values
        
    Returns:
        Discretized parameter values
    """
    discretized = {}
    for param_name, value in theta.items():
        precision = get_param_precision(param_name)
        # Round to nearest multiple of precision
        discretized[param_name] = round(value / precision) * precision
    
    return discretized

